Homework-04 is completed
Marki-Eriker/otus_hw pull request #7
Opened 2021-07-09 10:21 UTC by Marki-Eriker

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-07-11 06:02 UTC, kulti requested changes
Игорь, спасибо за вариант решения ДЗ. Как по мне, немножко многословно получилось из-за обилия if'oв на специфические кейзы.

Посмотрите, пожалуйста, на MoveToFront. Кажется, в нем ошибка. Из-за этого возвращаю на доработку.

Ссылка для проверяющего — https://otus.ru/teacher-lk/homework/211377/10916/

2021-07-11 06:02 UTC, kulti commented on hw04_lru_cache/list_test.go
> +		require.Equal(t, 4, l.Back().Value)
Можно написать хэлпер, который пробегает по списку и сравнивает, какие там элементы. Тогда тесты будут намного лучше читаться:
```
checkList(t, l, []int{1,2,3,4}

l.MoveToFront(l.Front())
checkList(t, l, []int{1,2,3,4}

l.MoveToFront(l.Back())
checkList(t, l, []int{4,1,2,3}
```

2021-07-12 10:48 UTC, Marki-Eriker commented on hw04_lru_cache/cache.go
> +		v.Value = item
Согласен, так более логично получается обновлять.

2021-07-12 10:48 UTC, Marki-Eriker commented on hw04_lru_cache/cache_test.go
> +		_ = c.Set("c", 900)
В принципе на это и проверял, только размышлял о нескольких обращений к элементам кэша и делал проверку, что по итогу переполнения, вытолкнет именно тот, который был затронут наиболее давно.

2021-07-12 10:48 UTC, Marki-Eriker commented on hw04_lru_cache/list.go
> +		return
Действительно такая проверка тут не имеет смысла, т.к. гарантия вызова методов от существующих элементов обеспечивается в методах самого кэша.

2021-07-12 10:48 UTC, Marki-Eriker commented on hw04_lru_cache/list.go
> +	if l.firstItem == i && l.firstItem.Next.Prev == i {
Аналогично предыдущему, согласен, что данная проверка будет лишней

2021-07-12 10:48 UTC, Marki-Eriker commented on hw04_lru_cache/list.go
> +	l.length--
Подумал как можно реализовать отталкиваясь от элементов соседей, получилось и правда короче.

2021-07-12 10:48 UTC, Marki-Eriker commented on hw04_lru_cache/list.go
> +	l.firstItem = i
Можно было использовать уже реализованную логику в методе Remove. Получилось на много короче и понятней.

2021-07-12 10:49 UTC, Marki-Eriker commented on hw04_lru_cache/list_test.go
> +		require.Equal(t, 4, l.Back().Value)
Написал подобную функцию, так действительно стало читаться удобней

2021-07-17 02:28 UTC, kulti requested changes
Игорь, круто поработали с кодом 👍 Только почему-то упустили, что нужно пофиксить ошибку в MoveToFront :)

2021-07-17 02:28 UTC, kulti commented on hw04_lru_cache/list.go
> +	if i.Value == nil {
Не понимаю эту проверку. Список хранит interface{}. nil — вполне себе нормальное значение для interface{}.

2021-07-17 02:28 UTC, kulti commented on hw04_lru_cache/list.go
> +	l.firstItem = i
Проблема никуда не ушла. i стал первым элементом, но i.Prev все еще имеет ссылку на другой элемент, хотя перед ним ничего нет.

2021-07-17 02:28 UTC, kulti commented on hw04_lru_cache/list_test.go
> +		t.Errorf("actual length: %d, expected: %d", l.Len(), len(v))
В тестах уже используется require. Не понимаю, зачем использовать стандартные методы для падения тестов.

2021-07-18 10:36 UTC, Marki-Eriker commented on hw04_lru_cache/list.go
> +	if i.Value == nil {
Согласен, проверка все-таки лишняя. методы кэша гарантируют что remove вызывается только с существующими элементами.

2021-07-18 11:17 UTC, Marki-Eriker commented on hw04_lru_cache/list_test.go
> +		t.Errorf("actual length: %d, expected: %d", l.Len(), len(v))
Действительно логичней использовать require, не подумал об этом сразу.

2021-07-18 11:23 UTC, Marki-Eriker commented on hw04_lru_cache/list.go
> +	l.firstItem = i
Проблему исправил. Следовало бы сразу в тестах проверять такое поведение. Тесты тоже обновлены

2021-07-25 05:58 UTC, kulti approved these changes
Игорь, спасибо за правки. Теперь решение корректное 👍 

Принято. Не хватает теста «на логику выталкивания давно используемых элементов». Поэтому 9 из 10.

2021-07-25 08:30 UTC, merged